# -*- coding: utf-8 -*-
"""controller.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Br1J1TX5RWAXPtCkv4zTwveJO9JNUVtV
"""

from hello_robot import HelloRobot  # Use Hello Robot's SDK

def capture_and_process():
    # Initialize robot
    robot = HelloRobot()

    # Capture image from robot's camera
    image_path = robot.camera.capture_image(save_path="image.png")

    # Query LLM for movement command
    command = query_llm(image_path)
    if command:
        direction, distance = parse_command(command)
        robot.move(direction, distance)

def parse_command(command: str) -> tuple:
    # Example command: "left 0.5" → ("left", 0.5)
    parts = command.split()
    return parts[0], float(parts[1])

if __name__ == "__main__":
    while not robot.object_found():
        capture_and_process()